name: test

on: [push, pull_request]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          uv-version: "0.6.1"
          python-version: "3.13"

      - run: uv sync --frozen
      - run: uv run pytest
      - run: uv run mypy --strict src tests